### ISSUE TITLE
Unable to connect UE with eNodeB using Docker Compose

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [srsran/srsRAN#673]
I am trying to run these step inside docker but it's failing.
https://docs.srslte.com/en/latest/app_notes/source/zeromq/source/index.html

```yaml
version: "3.9"

services:
  srsenb:
    image: shubhamtatvamasi/srsran-demo
    container_name: srsenb
    ipc: shareable
    cap_add:
      - SYS_NICE
    networks:
      srs_net:
        ipv4_address: 172.50.50.10
    command:
      - srsenb
      - --enb.mme_addr=192.168.60.142
      - --enb.gtp_bind_addr=172.50.50.10
      - --enb.s1c_bind_addr=172.50.50.10
      - --rf.device_name=zmq
      - --rf.device_args="fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://0.0.0.0:2001,id=enb,base_srate=23.04e6"

  srsue:
    image: shubhamtatvamasi/srsran-demo
    container_name: srsue
    depends_on: 
      - srsenb
    pid: service:srsenb
    ipc: service:srsenb
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    networks:
      srs_net:
        ipv4_address: 172.50.50.11
    command:
      - srsue
      - --usim.algo=milenage
      - --usim.opc=63BFA50EE6523365FF14C1F45F88737D
      - --rf.device_name=zmq
      - --rf.device_args="tx_port=tcp://*:2001,rx_port=tcp://0.0.0.0:2000,id=ue,base_srate=23.04e6"

networks:
  srs_net:
    ipam:
      driver: default
      config:
        - subnet: "172.50.50.0/24"
```

```
Attaching to srsenb, srsue
srsenb    | ---  Software Radio Systems LTE eNodeB  ---
srsenb    | 
srsenb    | Reading configuration file /etc/srsran/enb.conf...
srsenb    | 
srsenb    | Built in Release mode using 21.04.0.
srsenb    | 
srsenb    | Opening 1 channels in RF device=zmq with args="fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://0.0.0.0:2001,id=enb,base_srate=23.04e6"
srsue     | Reading configuration file /etc/srsran/ue.conf...
srsue     | 
srsue     | Built in Release mode using 21.04.0.
srsue     | 
srsue     | Opening 1 channels in RF device=zmq with args="tx_port=tcp://*:2001,rx_port=tcp://0.0.0.0:2000,id=ue,base_srate=23.04e6"
srsue     | CHx base_srate=23.04e6"
srsue     | CHx id=ue
srsue     | Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
srsue     | CH0 rx_port=tcp://0.0.0.0:2000
srsue     | CH0 tx_port=tcp://*:2001
srsenb    | CHx base_srate=23.04e6"
srsenb    | CHx id=enb
srsenb    | Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
srsenb    | CH0 rx_port=tcp://0.0.0.0:2001
srsenb    | CH0 tx_port=tcp://*:2000
srsenb    | CH0 fail_on_disconnect=true
srsenb    | Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
srsenb    | Current sample rate is 11.52 MHz with a base rate of 23.04 MHz (x2 decimation)
srsenb    | Setting frequency: DL=2680.0 Mhz, UL=2560.0 MHz for cc_idx=0 nof_prb=50
srsenb    | 
srsenb    | ==== eNodeB started ===
srsenb    | Type <t> to view trace
srsenb    | Closing stdin thread.
srsue     | Waiting PHY to initialize ... done!
srsue     | Attaching UE...
srsue     | Closing stdin thread.
```

It worked if I run them on same docker image.
